version: '3.1'
services:
  stats-server:
    build: statistics/service
    container_name: statistics_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATABASE_URL=jdbc:postgresql://stats-db:5432/stat
      - DATABASE_USER=stat
      - DATABASE_PASSWORD=stat

  stats-db:
    image: postgres:13.7-alpine
    container_name: statistics_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat

  ewm-service:
    build: main
    container_name: main_container
    ports:
      - "8080:8080"


