version: '3.1'
services:
  stats-server:
    build: statistics/service
    container_name: statistics_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics_of_visits

  stats-db:
    image: postgres:13.7-alpine
    container_name: statistics_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics_of_visits
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - SERVER_URL=http://statistics-server:9090
