version: '3.1'
services:
  stats-server:
    build: statistics/service
    container_name: statistics_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stat

  stats-db:
    image: postgres:13.7-alpine
    container_name: statistics_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=stat

  ewm-service:
    build: main
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - STATS_SERVER_URL=http://statistics-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm

  ewm-db:
    image: postgres:13.7-alpine
    container_name: main_db_container
    ports:
     - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm