DROP TABLE IF EXISTS statistics_of_visits;

CREATE TABLE IF NOT EXISTS statistics_of_visits (
    statistics_of_visits_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    ip varchar(255) NOT NULL,
    timestamp_of_query TIMESTAMP WITHOUT TIME ZONE
);