DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS compilations_events;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS categories (
    categories_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(100) NOT NULL,
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS users (
    users_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar(250) NOT NULL,
    email varchar(254) NOT NULL,
    CONSTRAINT UQ_USER_NAME UNIQUE (user_name),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
    events_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(2000),
    category_id BIGINT NOT NULL REFERENCES categories(categories_id) ON DELETE CASCADE,
    confirmed_requests BIGINT NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description varchar(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(users_id) ON DELETE CASCADE,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL,
    state varchar(9) NOT NULL,
    title varchar(120) NOT NULL,
    CONSTRAINT STATE_CONSTRAINT CHECK (state = 'PENDING' OR state = 'PUBLISHED' OR state = 'CANCELED')
);

CREATE TABLE IF NOT EXISTS participation_requests(
    participation_requests_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(events_id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(users_id) ON DELETE CASCADE,
    status varchar(9) NOT NULL,
    CONSTRAINT STATUS_CONSTRAINT CHECK (status = 'PENDING' OR status = 'CONFIRMED' OR status = 'REJECTED' OR status = 'CANCELED')
);

CREATE TABLE IF NOT EXISTS compilations (
    compilations_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(compilations_id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(events_id) ON DELETE CASCADE,
    CONSTRAINT pk PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments (
    comments_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT REFERENCES users(users_id),
    event_id BIGINT NOT NULL REFERENCES events(events_id) ON DELETE CASCADE,
    text varchar(10200) NOT NULL,
    created_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL
);